
--
-- CAPACITACION_SEQUENCE
--
 CREATE SEQUENCE "CAPACITACION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- CITA_SEQUENCE
--
 CREATE SEQUENCE "CITA_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- CIUDAD_SEQUENCE
--
 CREATE SEQUENCE "CIUDAD_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- COMUNA_SEQUENCE
--
 CREATE SEQUENCE "COMUNA_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- DIAGNOSTICO_SEQUENCE
--
 CREATE SEQUENCE "DIAGNOSTICO_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- EVALUACION_SEQUENCE
--
 CREATE SEQUENCE "EVALUACION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- EXAMEN_SEQUENCE
--
 CREATE SEQUENCE "EXAMEN_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- FECHACITA_SEQUENCE
--
 CREATE SEQUENCE "FECHACITA_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- HORAFECHACITA_SEQUENCE
--
 CREATE SEQUENCE "HORAFECHACITA_SEQUENCE" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- TIPO_USUARIO_SEQUENCE
--
 CREATE SEQUENCE "TIPO_USUARIO_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- TIPOEVALUACION_SEQUENCE
--
 CREATE SEQUENCE "TIPOEVALUACION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;
--
-- CAPACITACION
--
  CREATE TABLE "CAPACITACION" 
   (	"IDCAPACITACION" NUMBER(10,0) NOT NULL ENABLE,
	"OBJETIVO" VARCHAR2(255) NOT NULL ENABLE,
	"FECHA" TIMESTAMP(0) NOT NULL ENABLE,
	"LUGAR" VARCHAR2(255) NOT NULL ENABLE
   );
--
-- CITA
--
  CREATE TABLE "CITA" 
   (	"ID_CITA" NUMBER(10,0) NOT NULL ENABLE,
	"ASISTENCIA" CHAR(1) NOT NULL ENABLE,
	"RUT_MEDICO" VARCHAR2(9),
	"FECHA" DATE NOT NULL ENABLE,
	"HORA" TIMESTAMP(6) NOT NULL ENABLE,
	"ACTIVA" CHAR(1),
	CONSTRAINT "PK_ID_CITA" PRIMARY KEY ("ID_CITA") ENABLE
   );
--
-- CIUDAD
--
  CREATE TABLE "CIUDAD" 
   (	"IDCIUDAD" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- COMUNA
--
  CREATE TABLE "COMUNA" 
   (	"IDCOMUNA" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"IDCIUDAD" NUMBER(10,0) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- DETALLE_EVALUACION
--
  CREATE TABLE "DETALLE_EVALUACION" 
   (	"RECOMENDACION" VARCHAR2(255),
	"AUTORIZACION" CHAR(1) NOT NULL ENABLE,
	"ID_EVALUACION" NUMBER(10,0) NOT NULL ENABLE,
	"RUT_SAFE" VARCHAR2(9) NOT NULL ENABLE,
	PRIMARY KEY ("RECOMENDACION") ENABLE
   );
--
-- DETALLECAPACITACION
--
  CREATE TABLE "DETALLECAPACITACION" 
   (	"ASISTENCIA" CHAR(1) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(40) NOT NULL ENABLE,
	"IDCAPACITACION" NUMBER(10,0) NOT NULL ENABLE,
	"IDEMPLEADO" VARCHAR2(9) NOT NULL ENABLE
   );
--
-- DIAGNOSTICO
--
  CREATE TABLE "DIAGNOSTICO" 
   (	"ID_DIAGNOSTICO" NUMBER(10,0) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(300) NOT NULL ENABLE,
	"RUTEMPLEADO" VARCHAR2(9) NOT NULL ENABLE,
	"HABILITADO" CHAR(1) NOT NULL ENABLE,
	"ID_CITA" NUMBER(10,0),
	CONSTRAINT "PK_ID_DIAGNOSTICO" PRIMARY KEY ("ID_DIAGNOSTICO") ENABLE
   );
--
-- EMPLEADO
--
  CREATE TABLE "EMPLEADO" 
   (	"RUTEMPLEADO" VARCHAR2(9) NOT NULL ENABLE,
	"PNOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOP" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOM" VARCHAR2(30) NOT NULL ENABLE,
	"FNACIMIENTO" DATE NOT NULL ENABLE,
	"CORREO" VARCHAR2(30) NOT NULL ENABLE,
	"CLAVE" VARCHAR2(30) NOT NULL ENABLE,
	"NUMERO" NUMBER(9,0),
	"RUTEMPRESA" VARCHAR2(9) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- EMPLEADOSAFE
--
  CREATE TABLE "EMPLEADOSAFE" 
   (	"RUTSAFE" VARCHAR2(9) NOT NULL ENABLE,
	"PNOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOP" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOM" VARCHAR2(30) NOT NULL ENABLE,
	"FNACIMIENTO" DATE NOT NULL ENABLE,
	"CORREO" VARCHAR2(30) NOT NULL ENABLE,
	"CLAVE" VARCHAR2(30) NOT NULL ENABLE,
	"NUMERO" NUMBER(9,0),
	"IDTIPO" NUMBER(10,0) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- EMPRESA
--
  CREATE TABLE "EMPRESA" 
   (	"RUTEMPRESA" VARCHAR2(9) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"DIRECCION" VARCHAR2(50) NOT NULL ENABLE,
	"CORREO" VARCHAR2(30) NOT NULL ENABLE,
	"NUMERO" NUMBER(11,0) NOT NULL ENABLE,
	"IDCOMUNA" NUMBER(10,0) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- EVALUACION
--
  CREATE TABLE "EVALUACION" 
   (	"ID_EVALUACION" NUMBER(10,0) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"OBSERVACION" VARCHAR2(255) NOT NULL ENABLE,
	"DERIVADA" CHAR(1) NOT NULL ENABLE,
	"RUT_SAFE" VARCHAR2(9) NOT NULL ENABLE,
	"ID_TIPO" NUMBER(10,0) NOT NULL ENABLE,
	"RUT_EMPRESA" VARCHAR2(9) NOT NULL ENABLE,
	"RUT_EMPLEADO" VARCHAR2(9) NOT NULL ENABLE,
	"RECOMENDADA" CHAR(1) NOT NULL ENABLE,
	PRIMARY KEY ("ID_EVALUACION") ENABLE
   );
--
-- EXAMEN
--
  CREATE TABLE "EXAMEN" 
   (	"ID_EXAMEN" NUMBER(10,0),
	"NOMBRE" VARCHAR2(4000) NOT NULL ENABLE,
	"TIPO_DOC" VARCHAR2(4000) NOT NULL ENABLE,
	"DOCUMENTO" BLOB NOT NULL ENABLE,
	"ID_DIAGNOSTICO" NUMBER(10,0) NOT NULL ENABLE,
	"HABILITADO" CHAR(1) NOT NULL ENABLE,
	CONSTRAINT "PK_ID_EXAMEN" PRIMARY KEY ("ID_EXAMEN") ENABLE
   );
--
-- MEDICO
--
  CREATE TABLE "MEDICO" 
   (	"RUT_MEDICO" VARCHAR2(9) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOP" VARCHAR2(30) NOT NULL ENABLE,
	"APELLIDOM" VARCHAR2(30) NOT NULL ENABLE,
	"FNACIMIENTO" DATE NOT NULL ENABLE,
	"CORREO" VARCHAR2(40) NOT NULL ENABLE,
	"CLAVE" VARCHAR2(200) NOT NULL ENABLE,
	"TELEFONO" NUMBER(15,0) NOT NULL ENABLE,
	"ACTIVO" CHAR(1) NOT NULL ENABLE,
	"RUTEMPRESA" VARCHAR2(9) NOT NULL ENABLE,
	CONSTRAINT "PK_RUT_MEDICO" PRIMARY KEY ("RUT_MEDICO") ENABLE
   );
--
-- TIPOEVALUACION
--
  CREATE TABLE "TIPOEVALUACION" 
   (	"IDTIPO" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"HABILITADO" CHAR(1)
   );
--
-- TIPOUSUARIO
--
  CREATE TABLE "TIPOUSUARIO" 
   (	"IDTIPO" NUMBER(10,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE,
	"HABILITADA" CHAR(1)
   );
--
-- DIAGNOSTICOS_MEDICO_VIEW
--
CREATE OR REPLACE VIEW "DIAGNOSTICOS_MEDICO_VIEW" 
  AS 
  SELECT dg.id_diagnostico ID, dg.descripcion as DESCRIPCION, e.pnombre || ' ' || e.apellidop || ' ' || e.apellidom AS NOMBRE, dg.habilitado as HABILITADO,
  cta.fecha
FROM DIAGNOSTICO dg, CITA cta, EMPLEADO e
WHERE dg.id_cita = cta.id_cita AND e.rutempleado = dg.rutempleado;
--
-- DIAGNOSTICOS_TRABAJADOR_VIEW
--
CREATE OR REPLACE VIEW "DIAGNOSTICOS_TRABAJADOR_VIEW" 
  AS 
  SELECT dg.id_diagnostico ID, dg.descripcion as DESCRIPCION, e.pnombre || ' ' || e.apellidop || ' ' || e.apellidom AS NOMBRE, dg.habilitado as HABILITADO,
  cta.fecha AS FECHA, m.nombre || ' ' || m.apellidop || ' ' || m.apellidom AS MEDICO
FROM DIAGNOSTICO dg, CITA cta, EMPLEADO e, MEDICO m
WHERE dg.id_cita = cta.id_cita AND e.rutempleado = dg.rutempleado AND m.rut_medico = cta.rut_medico;
--
-- EMPLEADO_SAFE_VIEW
--
CREATE OR REPLACE VIEW "EMPLEADO_SAFE_VIEW" 
  AS 
  select rutsafe RUT, pnombre || ' ' || apellidop || ' ' || apellidom as NOMBRE, 
fnacimiento FECHA_NACIMIENTO, correo, numero, tip.nombre as TIPO_USUARIO, emp.HABILITADA
from empleadosafe emp, tipousuario tip
where emp.idtipo = tip.idtipo;
--
-- EMPLEADO_VIEW
--
CREATE OR REPLACE VIEW "EMPLEADO_VIEW" 
  AS 
  select emp.rutempleado RUT, PNOMBRE || ' ' || apellidop || ' ' || apellidom AS NOMBRE,
fnacimiento FECHA_NACIMIENTO, emp.CORREO, emp.NUMERO, empr.nombre as EMPRESA, emp.habilitada 
from empleado emp, empresa empr
where emp.rutempresa = empr.rutempresa;
--
-- EMPRESA_VIEW
--
CREATE OR REPLACE VIEW "EMPRESA_VIEW" 
  AS 
  select rutempresa as RUT, emp.nombre, direccion, correo, numero, comu.nombre as COMUNA,
emp.habilitada as HABILITADA
from empresa emp, comuna comu
where emp.idcomuna = comu.idcomuna;
--
-- EVALUACION_EMPRESA_VIEW
--
CREATE OR REPLACE VIEW "EVALUACION_EMPRESA_VIEW" 
  AS 
  select EVA.ID_EVALUACION CLAVE,eva.fecha FECHA, eva.observacion as OBSERVACION, DERIVADA, 
       emps.pnombre || ' ' || emps.apellidop as "EMPLEADO", tip.nombre TIPO,
       empr.nombre EMPRESA
from evaluacion eva, tipoevaluacion tip, empresa empr, empleadosafe emps
where eva.rut_safe = emps.rutsafe
and eva.id_tipo = tip.idtipo
and eva.rut_empresa = empr.rutempresa
AND tip.nombre = 'Instalación';
--
-- EVALUACION_PERSONA_VIEW
--
CREATE OR REPLACE VIEW "EVALUACION_PERSONA_VIEW" 
  AS 
  select EVA.ID_EVALUACION CLAVE,eva.fecha FECHA, eva.observacion as OBSERVACION, DERIVADA, 
       emps.pnombre || ' ' || emps.apellidop as "EMPLEADO", tip.nombre TIPO,
       empr.nombre EMPRESA, emp.pnombre || ' ' || emp.apellidop as CLIENTE
from evaluacion eva, tipoevaluacion tip, empresa empr, empleado emp, empleadosafe emps
where eva.rut_safe = emps.rutsafe
and eva.id_tipo = tip.idtipo
and eva.rut_empresa = empr.rutempresa
and eva.rut_empleado = emp.rutempleado
and nvl(eva.rut_empleado,0) != 0;
--
-- MEDICO_VIEW
--
CREATE OR REPLACE VIEW "MEDICO_VIEW" 
  AS 
  select rut_medico RUT, NOMBRE || ' ' || apellidop || ' ' || apellidom AS NOMBRE,
fnacimiento FECHA_NACIMIENTO, CORREO, TELEFONO as NUMERO, RUTEMPRESA, ACTIVO AS HABILITADA
from medico;
--
-- RECOMENDACIONES_EMPRESA_VIEW
--
CREATE OR REPLACE VIEW "RECOMENDACIONES_EMPRESA_VIEW" 
  AS 
  select EVA.ID_EVALUACION CLAVE,eva.fecha FECHA, eva.observacion as OBSERVACION, RECOMENDADA, 
        tip.nombre TIPO, empr.nombre EMPRESA
from evaluacion eva, tipoevaluacion tip, empresa empr, empleadosafe emps
where eva.rut_safe = emps.rutsafe
and eva.id_tipo = tip.idtipo
and eva.rut_empresa = empr.rutempresa
AND tip.nombre = 'Instalación'
and eva.derivada = 1;
--
-- RECOMENDACIONES_PERSONA_VIEW
--
CREATE OR REPLACE VIEW "RECOMENDACIONES_PERSONA_VIEW" 
  AS 
  select EVA.ID_EVALUACION CLAVE, eva.fecha FECHA, eva.observacion as OBSERVACION, RECOMENDADA, 
  empr.nombre EMPRESA, emp.pnombre || ' ' || emp.apellidop as CLIENTE
from evaluacion eva, tipoevaluacion tip, empresa empr, empleado emp, empleadosafe emps
where eva.rut_safe = emps.rutsafe
and eva.id_tipo = tip.idtipo
and eva.rut_empresa = empr.rutempresa
and eva.rut_empleado = emp.rutempleado
and nvl(eva.rut_empleado,0) != 0
and eva.derivada = 1;
--
-- RECOMENDADAS_VIEW
--
CREATE OR REPLACE VIEW "RECOMENDADAS_VIEW" 
  AS 
  select eva.id_evaluacion EVALUACION, EVA.FECHA, eva.observacion, det.recomendacion, det.autorizacion AUTORIZADA,
        eva.rut_safe EMPLEADO, eva.rut_empresa EMPRESA, eva.id_tipo TIPO, eva.rut_empleado CLIENTE
from evaluacion eva, detalle_evaluacion det
where eva.id_evaluacion = det.id_evaluacion;
--
-- VISTA_CITAS_GENERAL
--
CREATE OR REPLACE VIEW "VISTA_CITAS_GENERAL" 
  AS 
  SELECT cta.id_cita ID, med.RUT_MEDICO as RUT, med.NOMBRE || ' ' || med.APELLIDOP || ' ' || med.APELLIDOM AS NOMBRE, cta.FECHA,
cta.HORA, cta.asistencia, cta.activa
FROM MEDICO med, CITA cta
WHERE cta.rut_medico = med.rut_medico;
--
-- VISTA_EMPLEADOS
--
CREATE OR REPLACE VIEW "VISTA_EMPLEADOS" 
  AS 
  SELECT rutsafe RUT, pnombre || ' ' || apellidop || ' ' || apellidom as NOMBRE, 
fnacimiento FECHA_NACIMIENTO, correo, numero, tip.nombre as TIPO_USUARIO 
from empleadosafe emp, tipousuario tip
where emp.idtipo = tip.idtipo;
--
-- SYS_C007109
--
  CREATE UNIQUE INDEX "SYS_C007109" ON "CIUDAD" ("IDCIUDAD");
--
-- SYS_C007113
--
  CREATE UNIQUE INDEX "SYS_C007113" ON "COMUNA" ("IDCOMUNA");
--
-- SYS_C007121
--
  CREATE UNIQUE INDEX "SYS_C007121" ON "EMPRESA" ("RUTEMPRESA");
--
-- SYS_C007143
--
  CREATE UNIQUE INDEX "SYS_C007143" ON "TIPOUSUARIO" ("IDTIPO");
--
-- SYS_C007275
--
  CREATE UNIQUE INDEX "SYS_C007275" ON "CAPACITACION" ("IDCAPACITACION");
--
-- SYS_C007290
--
  CREATE UNIQUE INDEX "SYS_C007290" ON "EMPLEADOSAFE" ("RUTSAFE");
--
-- SYS_C007300
--
  CREATE UNIQUE INDEX "SYS_C007300" ON "EMPLEADO" ("RUTEMPLEADO");
--
-- SYS_C007316
--
  CREATE UNIQUE INDEX "SYS_C007316" ON "TIPOEVALUACION" ("IDTIPO");
--
-- SYS_C006997
--
ALTER TABLE "CAPACITACION" ADD  PRIMARY KEY ("IDCAPACITACION") ENABLE;

--
-- SYS_C007002
--
ALTER TABLE "CIUDAD" ADD  PRIMARY KEY ("IDCIUDAD") ENABLE;

--
-- SYS_C007005
--
ALTER TABLE "COMUNA" ADD  PRIMARY KEY ("IDCOMUNA") ENABLE;

--
-- SYS_C007015
--
ALTER TABLE "EMPLEADO" ADD  PRIMARY KEY ("RUTEMPLEADO") ENABLE;

--
-- SYS_C007024
--
ALTER TABLE "EMPLEADOSAFE" ADD  PRIMARY KEY ("RUTSAFE") ENABLE;

--
-- SYS_C007033
--
ALTER TABLE "EMPRESA" ADD  PRIMARY KEY ("RUTEMPRESA") ENABLE;

--
-- SYS_C007057
--
ALTER TABLE "TIPOEVALUACION" ADD  PRIMARY KEY ("IDTIPO") ENABLE;

--
-- SYS_C007060
--
ALTER TABLE "TIPOUSUARIO" ADD  PRIMARY KEY ("IDTIPO") ENABLE;

--
-- SYS_C007114
--
ALTER TABLE "CITA" ADD  FOREIGN KEY ("RUT_MEDICO") REFERENCES "MEDICO"("RUT_MEDICO") ENABLE;

--
-- SYS_C007140
--
ALTER TABLE "DETALLE_EVALUACION" ADD  FOREIGN KEY ("ID_EVALUACION") REFERENCES "EVALUACION"("ID_EVALUACION") ENABLE;

--
-- SYS_C007141
--
ALTER TABLE "DETALLE_EVALUACION" ADD  FOREIGN KEY ("RUT_SAFE") REFERENCES "EMPLEADOSAFE"("RUTSAFE") ENABLE;

--
-- SYS_C007075
--
ALTER TABLE "DIAGNOSTICO" ADD  FOREIGN KEY ("RUTEMPLEADO") REFERENCES "EMPLEADO"("RUTEMPLEADO") ENABLE;

--
-- SYS_C007115
--
ALTER TABLE "DIAGNOSTICO" ADD  FOREIGN KEY ("ID_CITA") REFERENCES "CITA"("ID_CITA") ENABLE;

--
-- SYS_C007133
--
ALTER TABLE "EVALUACION" ADD  FOREIGN KEY ("RUT_EMPRESA") REFERENCES "EMPRESA"("RUTEMPRESA") ENABLE;

--
-- SYS_C007134
--
ALTER TABLE "EVALUACION" ADD  FOREIGN KEY ("ID_TIPO") REFERENCES "TIPOEVALUACION"("IDTIPO") ENABLE;

--
-- SYS_C007135
--
ALTER TABLE "EVALUACION" ADD  FOREIGN KEY ("RUT_SAFE") REFERENCES "EMPLEADOSAFE"("RUTSAFE") ENABLE;

--
-- SYS_C007082
--
ALTER TABLE "EXAMEN" ADD  FOREIGN KEY ("ID_DIAGNOSTICO") REFERENCES "DIAGNOSTICO"("ID_DIAGNOSTICO") ENABLE;

--
-- MEDICO_FK1
--
ALTER TABLE "MEDICO" ADD CONSTRAINT "MEDICO_FK1" FOREIGN KEY ("RUTEMPRESA") REFERENCES "EMPRESA"("RUTEMPRESA") ENABLE;

--
-- DESHABILITAR_CITA
--
CREATE OR REPLACE PROCEDURE "DESHABILITAR_CITA" (id NUMBER, habilitada CHAR)
IS
BEGIN
  UPDATE CITA
  SET ACTIVA = habilitada
      WHERE ID_CITA = id;
  END;
/
--
-- DESHABILITAR_EMPLEADO
--
CREATE OR REPLACE PROCEDURE "DESHABILITAR_EMPLEADO" (rut VARCHAR2, habilitado char)
IS
BEGIN
 UPDATE EMPLEADO
  SET HABILITADA = habilitado
  WHERE RUTEMPLEADO = rut;
END;
/
--
-- DESHABILITAR_EMPLEADOSAFE
--
CREATE OR REPLACE PROCEDURE "DESHABILITAR_EMPLEADOSAFE" (rut VARCHAR2, habilitado char)
IS
BEGIN
 UPDATE EMPLEADOSAFE
  SET HABILITADA = habilitado
  WHERE RUTSAFE = rut;
END;
/
--
-- DESHABILITAR_EMPRESA
--
CREATE OR REPLACE PROCEDURE "DESHABILITAR_EMPRESA" (rut VARCHAR2, habilitado char)
IS
BEGIN
 UPDATE EMPRESA
  SET HABILITADA = habilitado
  WHERE RUTEMPRESA = rut;
END;
/
--
-- DESHABILITAR_MEDICO
--
CREATE OR REPLACE PROCEDURE "DESHABILITAR_MEDICO" (rut VARCHAR2, habilitado char)
IS
BEGIN
 UPDATE MEDICO
  SET ACTIVO = habilitado
  WHERE RUT_MEDICO = rut;
END;
/
--
-- INGRESAR_CAPACITACION
--
CREATE OR REPLACE PROCEDURE "INGRESAR_CAPACITACION" (OBJETIVO VARCHAR2, FECHA TIMESTAMP, 
LUGAR VARCHAR2)
IS
BEGIN
  insert into capacitacion(idcapacitacion, objetivo, fecha, lugar) values(CAPACITACION_SEQUENCE.nextval, objetivo, 
    fecha, LUGAR);
END;


/
--
-- INGRESAR_CITA
--
CREATE OR REPLACE PROCEDURE "INGRESAR_CITA" ( ASISTENCIA CHAR, RUT_MEDICO VARCHAR2, FECHA DATE, HORA TIMESTAMP, ACTIVA CHAR)
IS
BEGIN
  INSERT INTO CITA VALUES(CITA_sequence.nextval, ASISTENCIA, RUT_MEDICO, FECHA, HORA, ACTIVA);
  END;


/
--
-- INGRESAR_CIUDAD
--
CREATE OR REPLACE PROCEDURE "INGRESAR_CIUDAD" (nombre VARCHAR2)
IS
BEGIN
  INSERT INTO CIUDAD(IDCIUDAD, NOMBRE, HABILITADA)
     VALUES (CIUDAD_SEQUENCE.nextval,nombre, 1);
END;


/
--
-- INGRESAR_COMUNA
--
CREATE OR REPLACE PROCEDURE "INGRESAR_COMUNA" (nombre VARCHAR2, idciudad number)
IS
BEGIN
  INSERT INTO COMUNA(IDCOMUNA, NOMBRE, IDCIUDAD, HABILITADA)
     VALUES (COMUNA_SEQUENCE.nextval, nombre, idciudad, 1);
END;


/
--
-- INGRESAR_DETALLE_CAPACITACION
--
CREATE OR REPLACE PROCEDURE "INGRESAR_DETALLE_CAPACITACION" (ID_CAPACITACION NUMBER, RUT_EMPLEADO VARCHAR)
IS
BEGIN
  insert into detallecapacitacion(ASISTENCIA, ESTADO, IDCAPACITACION, IDEMPLEADO) values(0, '0', 
    id_capacitacion, rut_empleado);
END;


/
--
-- INGRESAR_DETALLE_EVALUACION
--
CREATE OR REPLACE PROCEDURE "INGRESAR_DETALLE_EVALUACION" (RECOMENDACION VARCHAR, AUTORIZACION CHAR, 
                            IDEVALUACION NUMBER, RUTEMPLEADO VARCHAR)
IS
BEGIN
  insert into detalle_evaluacion(RECOMENDACION, AUTORIZACION, id_evaluacion, rut_safe) 
  values(recomendacion, autorizacion, idevaluacion, rutempleado);
END;


/
--
-- INGRESAR_DIAGNOSTICO
--
CREATE OR REPLACE PROCEDURE "INGRESAR_DIAGNOSTICO" (DESCRIPCION VARCHAR, RUTEMPLEADO NUMBER, HABILITADO CHAR, ID_CITA NUMBER)
IS
BEGIN
    INSERT INTO DIAGNOSTICO VALUES(DIAGNOSTICO_SEQUENCE.NEXTVAL, DESCRIPCION, RUTEMPLEADO, HABILITADO, ID_CITA);
END;
/
--
-- INGRESAR_EMPLEADO
--
CREATE OR REPLACE PROCEDURE "INGRESAR_EMPLEADO" (rut VARCHAR2, nombre VARCHAR2, apellido_p VARCHAR2, 
apellido_m VARCHAR2, f_nacimiento DATE, correo VARCHAR2, clave VARCHAR2, numero number, rut_empresa varchar2)
IS
BEGIN
  INSERT INTO empleado(RUTEMPLEADO, PNOMBRE, APELLIDOP, APELLIDOM, FNACIMIENTO, CORREO, CLAVE, NUMERO, RUTEMPRESA, HABILITADA)
     VALUES (rut, nombre, apellido_p, apellido_m, to_date(f_nacimiento,'DD/MM/YY'), correo, clave, numero, rut_empresa, 1);
END;


/
--
-- INGRESAR_EMPLEADOSAFE
--
CREATE OR REPLACE PROCEDURE "INGRESAR_EMPLEADOSAFE" (rut VARCHAR2, nombre VARCHAR2, apellido_p VARCHAR2, 
apellido_m VARCHAR2, f_nacimiento DATE, correo VARCHAR2, clave VARCHAR2, numero number, id_tipo_usuario NUMBER)
IS
BEGIN
  INSERT INTO empleadosafe(RUTSAFE, PNOMBRE, APELLIDOP, APELLIDOM, FNACIMIENTO, CORREO, CLAVE, NUMERO, IDTIPO, HABILITADA)
     VALUES (rut, nombre, apellido_p, apellido_m, to_date(f_nacimiento,'DD/MM/YY'), correo, clave, numero, id_tipo_usuario, 1);
END;


/
--
-- INGRESAR_EMPRESA
--
CREATE OR REPLACE PROCEDURE "INGRESAR_EMPRESA" (rut VARCHAR2, nombre VARCHAR2, direccion VARCHAR2, 
correo VARCHAR2, numero number, idcomuna number)
IS
BEGIN
  INSERT INTO empresa(RUTEMPRESA, NOMBRE, DIRECCION, CORREO, NUMERO, IDCOMUNA, HABILITADA)
     VALUES (rut, nombre, direccion, correo, numero, idcomuna, 1);
END;


/
--
-- INGRESAR_EVALUACION
--
CREATE OR REPLACE PROCEDURE "INGRESAR_EVALUACION" (FECHA DATE, OBSERVACION VARCHAR, RUT_SAFE VARCHAR, 
                    ID_TIPO NUMERIC, RUT_EMPRESA VARCHAR, RUT_EMPLEADO VARCHAR)
IS
BEGIN
  insert into EVALUACION(ID_EVALUACION, FECHA, OBSERVACION, DERIVADA, RUT_SAFE, ID_TIPO, RUT_EMPRESA, RUT_EMPLEADO, RECOMENDADA) 
  values(EVALUACION_SEQUENCE.nextval, to_date(FECHA,'DD/MM/YY'),OBSERVACION, 0, RUT_SAFE, ID_TIPO, RUT_EMPRESA, RUT_EMPLEADO,'0');
END;


/
--
-- INGRESAR_EXAMEN
--
CREATE OR REPLACE PROCEDURE "INGRESAR_EXAMEN" (NOMBRE VARCHAR2, TIPO_DOC VARCHAR2, DOCUMENTO BLOB, ID_DIAGNOSTICO NUMERIC, HABILITADO CHAR)
IS
BEGIN
    INSERT INTO EXAMEN VALUES(EXAMEN_SEQUENCE.NEXTVAL, NOMBRE, TIPO_DOC, DOCUMENTO, ID_DIAGNOSTICO, HABILITADO);
END;


/
--
-- INGRESAR_MEDICO
--
CREATE OR REPLACE PROCEDURE "INGRESAR_MEDICO" (RUT_MEDICO VARCHAR2, NOMBRE  VARCHAR, APELLIDOP VARCHAR, APELLIDOM VARCHAR, FNACIMIENTO VARCHAR, CORREO VARCHAR,
CLAVE VARCHAR, TELEFONO NUMERIC, ACTIVO CHAR, RUTEMPRESA VARCHAR2)
IS
BEGIN
  INSERT INTO MEDICO VALUES (RUT_MEDICO, NOMBRE, APELLIDOP, APELLIDOM, FNACIMIENTO, CORREO, CLAVE, TELEFONO, ACTIVO, RUTEMPRESA);
END;


/
--
-- INGRESAR_TIPO_EVALUACION
--
CREATE OR REPLACE PROCEDURE "INGRESAR_TIPO_EVALUACION" (NOMBRE VARCHAR2)
IS
BEGIN
  insert into TIPOEVALUACION(idtipo, nombre, habilitado) values(tipoevaluacion_sequence.nextval, nombre, 1);
END;


/
--
-- INGRESAR_TIPO_USUARIO
--
CREATE OR REPLACE PROCEDURE "INGRESAR_TIPO_USUARIO" (nombre VARCHAR2, habilitada CHAR)
IS
BEGIN

  INSERT INTO tipousuario(IDTIPO, NOMBRE, HABILITADA)
  VALUES (tipo_usuario_sequence.nextval,nombre, habilitada);

END;


/
--
-- MODIFICAR_ASISTENCIA_CITA
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_ASISTENCIA_CITA" (id NUMBER, asis CHAR)
IS
BEGIN
  UPDATE CITA
  SET ASISTENCIA = asis
      WHERE ID_CITA = id;
  END;
/
--
-- MODIFICAR_CITA
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_CITA" (id NUMBER, asis CHAR, rut VARCHAR2, fecha_cta DATE, hora_cta TIMESTAMP, habilitada CHAR)
IS
BEGIN
  UPDATE CITA
  SET ASISTENCIA = asis,
      RUT_MEDICO = rut,
      FECHA = fecha_cta,
      HORA = hora_cta,
      ACTIVA = habilitada
      WHERE ID_CITA = id;
  END;


/
--
-- MODIFICAR_CIUDAD
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_CIUDAD" (id numBER, name VARCHAR2, activa char)
IS
BEGIN
 UPDATE CIUDAD
 SET NOMBRE = name,
     HABILITADA = activa
     WHERE IDCIUDAD = id;
END;


/
--
-- MODIFICAR_COMUNA
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_COMUNA" (id number, name VARCHAR2, id_ciudad number, activa char)
IS
BEGIN
 UPDATE COMUNA
 SET NOMBRE = name,
     IDCIUDAD = id_ciudad,
     HABILITADA = activa
     WHERE IDCOMUNA = id;
END;


/
--
-- MODIFICAR_DIAGNOSTICO
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_DIAGNOSTICO" (id number, descript VARCHAR, rut_empleado NUMERIC, activo CHAR, idcita NUMERIC)
IS
BEGIN
    UPDATE DIAGNOSTICO
    SET DESCRIPCION = descript,
        RUTEMPLEADO = rut_empleado,
        HABILITADO = activo,
        ID_CITA = idcita
        WHERE ID_DIAGNOSTICO = id;
END;


/
--
-- MODIFICAR_EMPLEADO
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_EMPLEADO" (rut VARCHAR2, nombre VARCHAR2, apellido_p VARCHAR2, 
apellido_m VARCHAR2, f_nacimiento DATE, email VARCHAR2, paswd VARCHAR2, fono number, rut_empresa varchar2, habilitado char)
IS
BEGIN
  UPDATE EMPLEADO
  SET PNOMBRE = nombre,
  APELLIDOP = apellido_p,
  APELLIDOM = apellido_m,
  FNACIMIENTO = f_nacimiento,
  CORREO =  email,
  CLAVE = paswd,
  NUMERO = fono,
  HABILITADA = habilitado
  WHERE RUTEMPLEADO = rut;
END;


/
--
-- MODIFICAR_EMPLEADOSAFE
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_EMPLEADOSAFE" (rut VARCHAR2, nombre VARCHAR2, apellido_p VARCHAR2, 
apellido_m VARCHAR2, f_nacimiento DATE, email VARCHAR2, paswd VARCHAR2, fono number, id_tipo_usuario NUMBER, habilitado char)
IS
BEGIN
 UPDATE EMPLEADOSAFE
  SET PNOMBRE = nombre,
   APELLIDOP = apellido_p,
   APELLIDOM = apellido_m,
   FNACIMIENTO = f_nacimiento,
   CORREO = email,
   CLAVE = paswd,
   NUMERO = fono,
   IDTIPO = id_tipo_usuario,
   HABILITADA = habilitado
  WHERE RUTSAFE = rut;
END;


/
--
-- MODIFICAR_EMPRESA
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_EMPRESA" (rut VARCHAR2, name VARCHAR2, direcc VARCHAR2, 
email VARCHAR2, fono number, idcomna number, habilitado char)
IS
BEGIN
  UPDATE EMPRESA
  SET NOMBRE = name,
      DIRECCION = direcc,
      CORREO = email,
      NUMERO = fono,
      IDCOMUNA = idcomna,
      HABILITADA = habilitado
      WHERE RUTEMPRESA = rut;
END;


/
--
-- MODIFICAR_EVALUACION
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_EVALUACION" (ID_EVAL NUMBER)
IS
BEGIN
  UPDATE EVALUACION 
  SET derivada = 1
  WHERE id_evaluacion = ID_EVAL;
END;


/
--
-- MODIFICAR_EXAMEN
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_EXAMEN" (id number, name VARCHAR2, tip_doc VARCHAR2, docmnt BLOB, iddiagnostico NUMERIC, activo CHAR)
IS
BEGIN
    UPDATE EXAMEN
    SET NOMBRE = name,
        TIPO_DOC = tip_doc,
        DOCUMENTO = docmnt,
        ID_DIAGNOSTICO = iddiagnostico,
        HABILITADO = activo
        WHERE ID_EXAMEN = id;
END;


/
--
-- MODIFICAR_MEDICO
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_MEDICO" (rut VARCHAR2, name  VARCHAR, apellido_p VARCHAR, apellido_m VARCHAR, f_nacimiento VARCHAR, 
email VARCHAR, paswd VARCHAR, fono NUMBER, habilitado CHAR, rut_empresa VARCHAR2)
IS
BEGIN
  UPDATE MEDICO
  SET NOMBRE = name,
      APELLIDOP = apellido_p,
      APELLIDOM = apellido_m,
      FNACIMIENTO = f_nacimiento,
      CORREO = email,
      CLAVE = paswd,
      TELEFONO = fono,
      ACTIVO = habilitado,
      RUTEMPRESA = rut_empresa
      WHERE RUT_MEDICO = rut;
END;


/
--
-- MODIFICAR_RECOMENDADO
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_RECOMENDADO" (ID_EVAL NUMBER)
IS
BEGIN
  UPDATE EVALUACION 
  SET RECOMENDADA = 1
  WHERE id_evaluacion = ID_EVAL;
END;


/
--
-- MODIFICAR_TIPO_USUARIO
--
CREATE OR REPLACE PROCEDURE "MODIFICAR_TIPO_USUARIO" (idtipous NUMBER, name VARCHAR2, habilitado CHAR)
IS
BEGIN
  UPDATE TIPOUSUARIO
  SET NOMBRE = name, 
  HABILITADA = habilitado 
  WHERE IDTIPO = idtipous;
END;


/
