//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO
    {
        public Nullable<decimal> IDCAPACITACION { get; set; }
        public string RUTEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO_DOC { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public decimal IDCERTIFICADO { get; set; }
    }
}
