//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public CITA()
        {
            this.DIAGNOSTICO = new HashSet<DIAGNOSTICO>();
        }
    
        public int ID_CITA { get; set; }
        public string ASISTENCIA { get; set; }
        public string RUT_MEDICO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public string ACTIVA { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICO { get; set; }
    }
}
