//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_EVALUACION
    {
        public string RECOMENDACION { get; set; }
        public string AUTORIZACION { get; set; }
        public int ID_EVALUACION { get; set; }
        public string RUT_SAFE { get; set; }
    
        public virtual EVALUACION EVALUACION { get; set; }
        public virtual EMPLEADOSAFE EMPLEADOSAFE { get; set; }
    }
}
