//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        public DIAGNOSTICO()
        {
            this.EXAMEN = new HashSet<EXAMEN>();
        }
    
        public int ID_DIAGNOSTICO { get; set; }
        public string DESCRIPCION { get; set; }
        public string RUTEMPLEADO { get; set; }
        public string HABILITADO { get; set; }
        public Nullable<int> ID_CITA { get; set; }
    
        public virtual CITA CITA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<EXAMEN> EXAMEN { get; set; }
    }
}
