//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOSAFE
    {
        public EMPLEADOSAFE()
        {
            this.DETALLE_EVALUACION = new HashSet<DETALLE_EVALUACION>();
            this.EVALUACION = new HashSet<EVALUACION>();
        }
    
        public string RUTSAFE { get; set; }
        public string PNOMBRE { get; set; }
        public string APELLIDOP { get; set; }
        public string APELLIDOM { get; set; }
        public System.DateTime FNACIMIENTO { get; set; }
        public string CORREO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public int IDTIPO { get; set; }
        public string HABILITADA { get; set; }
    
        public virtual ICollection<DETALLE_EVALUACION> DETALLE_EVALUACION { get; set; }
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
    }
}
