//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.DIAGNOSTICO = new HashSet<DIAGNOSTICO>();
            this.DETALLECAPACITACION = new HashSet<DETALLECAPACITACION>();
        }
    
        public string RUTEMPLEADO { get; set; }
        public string PNOMBRE { get; set; }
        public string APELLIDOP { get; set; }
        public string APELLIDOM { get; set; }
        public System.DateTime FNACIMIENTO { get; set; }
        public string CORREO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string RUTEMPRESA { get; set; }
        public string HABILITADA { get; set; }
    
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual ICollection<DETALLECAPACITACION> DETALLECAPACITACION { get; set; }
    }
}
