//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_VIEW
    {
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public long NUMERO { get; set; }
        public string COMUNA { get; set; }
        public string HABILITADA { get; set; }
    }
}
