//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACION
    {
        public EVALUACION()
        {
            this.DETALLE_EVALUACION = new HashSet<DETALLE_EVALUACION>();
        }
    
        public int ID_EVALUACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OBSERVACION { get; set; }
        public string DERIVADA { get; set; }
        public string RUT_SAFE { get; set; }
        public int ID_TIPO { get; set; }
        public string RUT_EMPRESA { get; set; }
        public string RECOMENDADA { get; set; }
    
        public virtual ICollection<DETALLE_EVALUACION> DETALLE_EVALUACION { get; set; }
        public virtual EMPLEADOSAFE EMPLEADOSAFE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPOEVALUACION TIPOEVALUACION { get; set; }
    }
}
