//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN
    {
        public int ID_EXAMEN { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO_DOC { get; set; }
        public byte[] DOCUMENTO { get; set; }
        public int ID_DIAGNOSTICO { get; set; }
        public string HABILITADO { get; set; }
        public string ANOTACION { get; set; }
    
        public virtual DIAGNOSTICO DIAGNOSTICO { get; set; }
    }
}
