//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.CITA = new HashSet<CITA>();
        }
    
        public string RUT_MEDICO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOP { get; set; }
        public string APELLIDOM { get; set; }
        public System.DateTime FNACIMIENTO { get; set; }
        public string CORREO { get; set; }
        public string CLAVE { get; set; }
        public long TELEFONO { get; set; }
        public string ACTIVO { get; set; }
        public string RUTEMPRESA { get; set; }
    
        public virtual ICollection<CITA> CITA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
