//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CITA> CITA { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_EVALUACION> DETALLE_EVALUACION { get; set; }
        public DbSet<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<EMPLEADOSAFE> EMPLEADOSAFE { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<EVALUACION> EVALUACION { get; set; }
        public DbSet<EXAMEN> EXAMEN { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<TIPOEVALUACION> TIPOEVALUACION { get; set; }
        public DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public DbSet<DETALLECAPACITACION> DETALLECAPACITACION { get; set; }
        public DbSet<DIAGNOSTICOS_MEDICO_VIEW> DIAGNOSTICOS_MEDICO_VIEW { get; set; }
        public DbSet<DIAGNOSTICOS_TRABAJADOR_VIEW> DIAGNOSTICOS_TRABAJADOR_VIEW { get; set; }
        public DbSet<EMPLEADO_SAFE_VIEW> EMPLEADO_SAFE_VIEW { get; set; }
        public DbSet<EMPLEADO_VIEW> EMPLEADO_VIEW { get; set; }
        public DbSet<EMPRESA_VIEW> EMPRESA_VIEW { get; set; }
        public DbSet<EVALUACIONES_VIEW> EVALUACIONES_VIEW { get; set; }
        public DbSet<EXAMENES_MEDICO_VIEW> EXAMENES_MEDICO_VIEW { get; set; }
        public DbSet<MEDICO_VIEW> MEDICO_VIEW { get; set; }
        public DbSet<RECOMENDADAS_VIEW> RECOMENDADAS_VIEW { get; set; }
        public DbSet<VISTA_CITAS_GENERAL> VISTA_CITAS_GENERAL { get; set; }
    
        public virtual int DESHABILITAR_CITA(Nullable<decimal> iD, string hABILITADA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var hABILITADAParameter = hABILITADA != null ?
                new ObjectParameter("HABILITADA", hABILITADA) :
                new ObjectParameter("HABILITADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_CITA", iDParameter, hABILITADAParameter);
        }
    
        public virtual int DESHABILITAR_DIAGNOSTICO(Nullable<decimal> iD, string hABILITADA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var hABILITADAParameter = hABILITADA != null ?
                new ObjectParameter("HABILITADA", hABILITADA) :
                new ObjectParameter("HABILITADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_DIAGNOSTICO", iDParameter, hABILITADAParameter);
        }
    
        public virtual int DESHABILITAR_EMPLEADO(string rUT, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_EMPLEADO", rUTParameter, hABILITADOParameter);
        }
    
        public virtual int DESHABILITAR_EMPLEADOSAFE(string rUT, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_EMPLEADOSAFE", rUTParameter, hABILITADOParameter);
        }
    
        public virtual int DESHABILITAR_EMPRESA(string rUT, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_EMPRESA", rUTParameter, hABILITADOParameter);
        }
    
        public virtual int DESHABILITAR_MEDICO(string rUT, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESHABILITAR_MEDICO", rUTParameter, hABILITADOParameter);
        }
    
        public virtual int ELIMINAR_EVALUACION(Nullable<decimal> iD_EV)
        {
            var iD_EVParameter = iD_EV.HasValue ?
                new ObjectParameter("ID_EV", iD_EV) :
                new ObjectParameter("ID_EV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_EVALUACION", iD_EVParameter);
        }
    
        public virtual int ELIMINAR_EXAMEN(Nullable<decimal> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_EXAMEN", iDParameter);
        }
    
        public virtual int ELIMINAR_TIPO_EVALUACION(Nullable<decimal> iDTIPOEV, string eSTADO)
        {
            var iDTIPOEVParameter = iDTIPOEV.HasValue ?
                new ObjectParameter("IDTIPOEV", iDTIPOEV) :
                new ObjectParameter("IDTIPOEV", typeof(decimal));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TIPO_EVALUACION", iDTIPOEVParameter, eSTADOParameter);
        }
    
        public virtual int INGRESAR_CAPACITACION(string oBJETIVO, Nullable<System.DateTime> fECHA, string lUGAR)
        {
            var oBJETIVOParameter = oBJETIVO != null ?
                new ObjectParameter("OBJETIVO", oBJETIVO) :
                new ObjectParameter("OBJETIVO", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var lUGARParameter = lUGAR != null ?
                new ObjectParameter("LUGAR", lUGAR) :
                new ObjectParameter("LUGAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_CAPACITACION", oBJETIVOParameter, fECHAParameter, lUGARParameter);
        }
    
        public virtual int INGRESAR_CITA(string aSISTENCIA, string rUT_MEDICO, Nullable<System.DateTime> fECHA, Nullable<System.DateTime> hORA, string aCTIVA)
        {
            var aSISTENCIAParameter = aSISTENCIA != null ?
                new ObjectParameter("ASISTENCIA", aSISTENCIA) :
                new ObjectParameter("ASISTENCIA", typeof(string));
    
            var rUT_MEDICOParameter = rUT_MEDICO != null ?
                new ObjectParameter("RUT_MEDICO", rUT_MEDICO) :
                new ObjectParameter("RUT_MEDICO", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var hORAParameter = hORA.HasValue ?
                new ObjectParameter("HORA", hORA) :
                new ObjectParameter("HORA", typeof(System.DateTime));
    
            var aCTIVAParameter = aCTIVA != null ?
                new ObjectParameter("ACTIVA", aCTIVA) :
                new ObjectParameter("ACTIVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_CITA", aSISTENCIAParameter, rUT_MEDICOParameter, fECHAParameter, hORAParameter, aCTIVAParameter);
        }
    
        public virtual int INGRESAR_CIUDAD(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_CIUDAD", nOMBREParameter);
        }
    
        public virtual int INGRESAR_COMUNA(string nOMBRE, Nullable<decimal> iDCIUDAD)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDCIUDADParameter = iDCIUDAD.HasValue ?
                new ObjectParameter("IDCIUDAD", iDCIUDAD) :
                new ObjectParameter("IDCIUDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_COMUNA", nOMBREParameter, iDCIUDADParameter);
        }
    
        public virtual int INGRESAR_DETALLE_CAPACITACION(Nullable<decimal> iD_CAPACITACION, string rUT_EMPLEADO)
        {
            var iD_CAPACITACIONParameter = iD_CAPACITACION.HasValue ?
                new ObjectParameter("ID_CAPACITACION", iD_CAPACITACION) :
                new ObjectParameter("ID_CAPACITACION", typeof(decimal));
    
            var rUT_EMPLEADOParameter = rUT_EMPLEADO != null ?
                new ObjectParameter("RUT_EMPLEADO", rUT_EMPLEADO) :
                new ObjectParameter("RUT_EMPLEADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_DETALLE_CAPACITACION", iD_CAPACITACIONParameter, rUT_EMPLEADOParameter);
        }
    
        public virtual int INGRESAR_DETALLE_EVALUACION(string rECOMENDACION, string aUTORIZACION, Nullable<decimal> iDEVALUACION, string rUTEMPLEADO)
        {
            var rECOMENDACIONParameter = rECOMENDACION != null ?
                new ObjectParameter("RECOMENDACION", rECOMENDACION) :
                new ObjectParameter("RECOMENDACION", typeof(string));
    
            var aUTORIZACIONParameter = aUTORIZACION != null ?
                new ObjectParameter("AUTORIZACION", aUTORIZACION) :
                new ObjectParameter("AUTORIZACION", typeof(string));
    
            var iDEVALUACIONParameter = iDEVALUACION.HasValue ?
                new ObjectParameter("IDEVALUACION", iDEVALUACION) :
                new ObjectParameter("IDEVALUACION", typeof(decimal));
    
            var rUTEMPLEADOParameter = rUTEMPLEADO != null ?
                new ObjectParameter("RUTEMPLEADO", rUTEMPLEADO) :
                new ObjectParameter("RUTEMPLEADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_DETALLE_EVALUACION", rECOMENDACIONParameter, aUTORIZACIONParameter, iDEVALUACIONParameter, rUTEMPLEADOParameter);
        }
    
        public virtual int INGRESAR_DIAGNOSTICO(string dESCRIPCION, Nullable<decimal> rUTEMPLEADO, string hABILITADO, Nullable<decimal> iD_CITA)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rUTEMPLEADOParameter = rUTEMPLEADO.HasValue ?
                new ObjectParameter("RUTEMPLEADO", rUTEMPLEADO) :
                new ObjectParameter("RUTEMPLEADO", typeof(decimal));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            var iD_CITAParameter = iD_CITA.HasValue ?
                new ObjectParameter("ID_CITA", iD_CITA) :
                new ObjectParameter("ID_CITA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_DIAGNOSTICO", dESCRIPCIONParameter, rUTEMPLEADOParameter, hABILITADOParameter, iD_CITAParameter);
        }
    
        public virtual int INGRESAR_EMPLEADO(string rUT, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<System.DateTime> f_NACIMIENTO, string cORREO, string cLAVE, Nullable<decimal> nUMERO, string rUT_EMPRESA)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var f_NACIMIENTOParameter = f_NACIMIENTO.HasValue ?
                new ObjectParameter("F_NACIMIENTO", f_NACIMIENTO) :
                new ObjectParameter("F_NACIMIENTO", typeof(System.DateTime));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var nUMEROParameter = nUMERO.HasValue ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(decimal));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_EMPLEADO", rUTParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, f_NACIMIENTOParameter, cORREOParameter, cLAVEParameter, nUMEROParameter, rUT_EMPRESAParameter);
        }
    
        public virtual int INGRESAR_EMPLEADOSAFE(string rUT, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<System.DateTime> f_NACIMIENTO, string cORREO, string cLAVE, Nullable<decimal> nUMERO, Nullable<decimal> iD_TIPO_USUARIO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var f_NACIMIENTOParameter = f_NACIMIENTO.HasValue ?
                new ObjectParameter("F_NACIMIENTO", f_NACIMIENTO) :
                new ObjectParameter("F_NACIMIENTO", typeof(System.DateTime));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var nUMEROParameter = nUMERO.HasValue ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(decimal));
    
            var iD_TIPO_USUARIOParameter = iD_TIPO_USUARIO.HasValue ?
                new ObjectParameter("ID_TIPO_USUARIO", iD_TIPO_USUARIO) :
                new ObjectParameter("ID_TIPO_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_EMPLEADOSAFE", rUTParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, f_NACIMIENTOParameter, cORREOParameter, cLAVEParameter, nUMEROParameter, iD_TIPO_USUARIOParameter);
        }
    
        public virtual int INGRESAR_EMPRESA(string rUT, string nOMBRE, string dIRECCION, string cORREO, Nullable<decimal> nUMERO, Nullable<decimal> iDCOMUNA)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var nUMEROParameter = nUMERO.HasValue ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(decimal));
    
            var iDCOMUNAParameter = iDCOMUNA.HasValue ?
                new ObjectParameter("IDCOMUNA", iDCOMUNA) :
                new ObjectParameter("IDCOMUNA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_EMPRESA", rUTParameter, nOMBREParameter, dIRECCIONParameter, cORREOParameter, nUMEROParameter, iDCOMUNAParameter);
        }
    
        public virtual int INGRESAR_EVALUACION(Nullable<System.DateTime> fECHA, string oBSERVACION, string rUT_SAFE, Nullable<decimal> iD_TIPO, string rUT_EMPRESA)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var oBSERVACIONParameter = oBSERVACION != null ?
                new ObjectParameter("OBSERVACION", oBSERVACION) :
                new ObjectParameter("OBSERVACION", typeof(string));
    
            var rUT_SAFEParameter = rUT_SAFE != null ?
                new ObjectParameter("RUT_SAFE", rUT_SAFE) :
                new ObjectParameter("RUT_SAFE", typeof(string));
    
            var iD_TIPOParameter = iD_TIPO.HasValue ?
                new ObjectParameter("ID_TIPO", iD_TIPO) :
                new ObjectParameter("ID_TIPO", typeof(decimal));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_EVALUACION", fECHAParameter, oBSERVACIONParameter, rUT_SAFEParameter, iD_TIPOParameter, rUT_EMPRESAParameter);
        }
    
        public virtual int INGRESAR_EXAMEN(string nOMBRE, string tIPO_DOC, byte[] dOCUMENTO, Nullable<decimal> iD_DIAGNOSTICO, string hABILITADO, string aNOTACION)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var tIPO_DOCParameter = tIPO_DOC != null ?
                new ObjectParameter("TIPO_DOC", tIPO_DOC) :
                new ObjectParameter("TIPO_DOC", typeof(string));
    
            var dOCUMENTOParameter = dOCUMENTO != null ?
                new ObjectParameter("DOCUMENTO", dOCUMENTO) :
                new ObjectParameter("DOCUMENTO", typeof(byte[]));
    
            var iD_DIAGNOSTICOParameter = iD_DIAGNOSTICO.HasValue ?
                new ObjectParameter("ID_DIAGNOSTICO", iD_DIAGNOSTICO) :
                new ObjectParameter("ID_DIAGNOSTICO", typeof(decimal));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            var aNOTACIONParameter = aNOTACION != null ?
                new ObjectParameter("ANOTACION", aNOTACION) :
                new ObjectParameter("ANOTACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_EXAMEN", nOMBREParameter, tIPO_DOCParameter, dOCUMENTOParameter, iD_DIAGNOSTICOParameter, hABILITADOParameter, aNOTACIONParameter);
        }
    
        public virtual int INGRESAR_MEDICO(string rUT_MEDICO, string nOMBRE, string aPELLIDOP, string aPELLIDOM, string fNACIMIENTO, string cORREO, string cLAVE, Nullable<decimal> tELEFONO, string aCTIVO, string rUTEMPRESA)
        {
            var rUT_MEDICOParameter = rUT_MEDICO != null ?
                new ObjectParameter("RUT_MEDICO", rUT_MEDICO) :
                new ObjectParameter("RUT_MEDICO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var fNACIMIENTOParameter = fNACIMIENTO != null ?
                new ObjectParameter("FNACIMIENTO", fNACIMIENTO) :
                new ObjectParameter("FNACIMIENTO", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            var rUTEMPRESAParameter = rUTEMPRESA != null ?
                new ObjectParameter("RUTEMPRESA", rUTEMPRESA) :
                new ObjectParameter("RUTEMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_MEDICO", rUT_MEDICOParameter, nOMBREParameter, aPELLIDOPParameter, aPELLIDOMParameter, fNACIMIENTOParameter, cORREOParameter, cLAVEParameter, tELEFONOParameter, aCTIVOParameter, rUTEMPRESAParameter);
        }
    
        public virtual int INGRESAR_TIPO_EVALUACION(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_TIPO_EVALUACION", nOMBREParameter);
        }
    
        public virtual int INGRESAR_TIPO_USUARIO(string nOMBRE, string hABILITADA)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var hABILITADAParameter = hABILITADA != null ?
                new ObjectParameter("HABILITADA", hABILITADA) :
                new ObjectParameter("HABILITADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_TIPO_USUARIO", nOMBREParameter, hABILITADAParameter);
        }
    
        public virtual int MODIFICAR_ASISTENCIA_CITA(Nullable<decimal> iD, string aSIS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var aSISParameter = aSIS != null ?
                new ObjectParameter("ASIS", aSIS) :
                new ObjectParameter("ASIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_ASISTENCIA_CITA", iDParameter, aSISParameter);
        }
    
        public virtual int MODIFICAR_CITA(Nullable<decimal> iD, string aSIS, string rUT, Nullable<System.DateTime> fECHA_CTA, Nullable<System.DateTime> hORA_CTA, string hABILITADA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var aSISParameter = aSIS != null ?
                new ObjectParameter("ASIS", aSIS) :
                new ObjectParameter("ASIS", typeof(string));
    
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var fECHA_CTAParameter = fECHA_CTA.HasValue ?
                new ObjectParameter("FECHA_CTA", fECHA_CTA) :
                new ObjectParameter("FECHA_CTA", typeof(System.DateTime));
    
            var hORA_CTAParameter = hORA_CTA.HasValue ?
                new ObjectParameter("HORA_CTA", hORA_CTA) :
                new ObjectParameter("HORA_CTA", typeof(System.DateTime));
    
            var hABILITADAParameter = hABILITADA != null ?
                new ObjectParameter("HABILITADA", hABILITADA) :
                new ObjectParameter("HABILITADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_CITA", iDParameter, aSISParameter, rUTParameter, fECHA_CTAParameter, hORA_CTAParameter, hABILITADAParameter);
        }
    
        public virtual int MODIFICAR_CIUDAD(Nullable<decimal> iD, string nAME, string aCTIVA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var aCTIVAParameter = aCTIVA != null ?
                new ObjectParameter("ACTIVA", aCTIVA) :
                new ObjectParameter("ACTIVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_CIUDAD", iDParameter, nAMEParameter, aCTIVAParameter);
        }
    
        public virtual int MODIFICAR_COMUNA(Nullable<decimal> iD, string nAME, Nullable<decimal> iD_CIUDAD, string aCTIVA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var iD_CIUDADParameter = iD_CIUDAD.HasValue ?
                new ObjectParameter("ID_CIUDAD", iD_CIUDAD) :
                new ObjectParameter("ID_CIUDAD", typeof(decimal));
    
            var aCTIVAParameter = aCTIVA != null ?
                new ObjectParameter("ACTIVA", aCTIVA) :
                new ObjectParameter("ACTIVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_COMUNA", iDParameter, nAMEParameter, iD_CIUDADParameter, aCTIVAParameter);
        }
    
        public virtual int MODIFICAR_DIAGNOSTICO(Nullable<decimal> iD, string dESCRIPT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var dESCRIPTParameter = dESCRIPT != null ?
                new ObjectParameter("DESCRIPT", dESCRIPT) :
                new ObjectParameter("DESCRIPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_DIAGNOSTICO", iDParameter, dESCRIPTParameter);
        }
    
        public virtual int MODIFICAR_EMPLEADO(string rUT, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<System.DateTime> f_NACIMIENTO, string eMAIL, string pASWD, Nullable<decimal> fONO, string rUT_EMPRESA, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var f_NACIMIENTOParameter = f_NACIMIENTO.HasValue ?
                new ObjectParameter("F_NACIMIENTO", f_NACIMIENTO) :
                new ObjectParameter("F_NACIMIENTO", typeof(System.DateTime));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASWDParameter = pASWD != null ?
                new ObjectParameter("PASWD", pASWD) :
                new ObjectParameter("PASWD", typeof(string));
    
            var fONOParameter = fONO.HasValue ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(decimal));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_EMPLEADO", rUTParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, f_NACIMIENTOParameter, eMAILParameter, pASWDParameter, fONOParameter, rUT_EMPRESAParameter, hABILITADOParameter);
        }
    
        public virtual int MODIFICAR_EMPLEADOSAFE(string rUT, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<System.DateTime> f_NACIMIENTO, string eMAIL, string pASWD, Nullable<decimal> fONO, Nullable<decimal> iD_TIPO_USUARIO, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var f_NACIMIENTOParameter = f_NACIMIENTO.HasValue ?
                new ObjectParameter("F_NACIMIENTO", f_NACIMIENTO) :
                new ObjectParameter("F_NACIMIENTO", typeof(System.DateTime));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASWDParameter = pASWD != null ?
                new ObjectParameter("PASWD", pASWD) :
                new ObjectParameter("PASWD", typeof(string));
    
            var fONOParameter = fONO.HasValue ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(decimal));
    
            var iD_TIPO_USUARIOParameter = iD_TIPO_USUARIO.HasValue ?
                new ObjectParameter("ID_TIPO_USUARIO", iD_TIPO_USUARIO) :
                new ObjectParameter("ID_TIPO_USUARIO", typeof(decimal));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_EMPLEADOSAFE", rUTParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, f_NACIMIENTOParameter, eMAILParameter, pASWDParameter, fONOParameter, iD_TIPO_USUARIOParameter, hABILITADOParameter);
        }
    
        public virtual int MODIFICAR_EMPRESA(string rUT, string nAME, string dIRECC, string eMAIL, Nullable<decimal> fONO, Nullable<decimal> iDCOMNA, string hABILITADO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var dIRECCParameter = dIRECC != null ?
                new ObjectParameter("DIRECC", dIRECC) :
                new ObjectParameter("DIRECC", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fONOParameter = fONO.HasValue ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(decimal));
    
            var iDCOMNAParameter = iDCOMNA.HasValue ?
                new ObjectParameter("IDCOMNA", iDCOMNA) :
                new ObjectParameter("IDCOMNA", typeof(decimal));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_EMPRESA", rUTParameter, nAMEParameter, dIRECCParameter, eMAILParameter, fONOParameter, iDCOMNAParameter, hABILITADOParameter);
        }
    
        public virtual int MODIFICAR_ESTADO_EVALUACION(Nullable<decimal> iD_EVAL)
        {
            var iD_EVALParameter = iD_EVAL.HasValue ?
                new ObjectParameter("ID_EVAL", iD_EVAL) :
                new ObjectParameter("ID_EVAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_ESTADO_EVALUACION", iD_EVALParameter);
        }
    
        public virtual int MODIFICAR_EVALUACION(Nullable<decimal> iD_EVAL, Nullable<System.DateTime> fECHA, string oBSERV, string rUTSAFE, Nullable<decimal> iDTIPO, string rUT_EMPRESA)
        {
            var iD_EVALParameter = iD_EVAL.HasValue ?
                new ObjectParameter("ID_EVAL", iD_EVAL) :
                new ObjectParameter("ID_EVAL", typeof(decimal));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var oBSERVParameter = oBSERV != null ?
                new ObjectParameter("OBSERV", oBSERV) :
                new ObjectParameter("OBSERV", typeof(string));
    
            var rUTSAFEParameter = rUTSAFE != null ?
                new ObjectParameter("RUTSAFE", rUTSAFE) :
                new ObjectParameter("RUTSAFE", typeof(string));
    
            var iDTIPOParameter = iDTIPO.HasValue ?
                new ObjectParameter("IDTIPO", iDTIPO) :
                new ObjectParameter("IDTIPO", typeof(decimal));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_EVALUACION", iD_EVALParameter, fECHAParameter, oBSERVParameter, rUTSAFEParameter, iDTIPOParameter, rUT_EMPRESAParameter);
        }
    
        public virtual int MODIFICAR_EXAMEN(Nullable<decimal> iD, string nAME, string tIP_DOC, byte[] dOCMNT, string aNOTACIONES)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var tIP_DOCParameter = tIP_DOC != null ?
                new ObjectParameter("TIP_DOC", tIP_DOC) :
                new ObjectParameter("TIP_DOC", typeof(string));
    
            var dOCMNTParameter = dOCMNT != null ?
                new ObjectParameter("DOCMNT", dOCMNT) :
                new ObjectParameter("DOCMNT", typeof(byte[]));
    
            var aNOTACIONESParameter = aNOTACIONES != null ?
                new ObjectParameter("ANOTACIONES", aNOTACIONES) :
                new ObjectParameter("ANOTACIONES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_EXAMEN", iDParameter, nAMEParameter, tIP_DOCParameter, dOCMNTParameter, aNOTACIONESParameter);
        }
    
        public virtual int MODIFICAR_MEDICO(string rUT, string nAME, string aPELLIDO_P, string aPELLIDO_M, string f_NACIMIENTO, string eMAIL, string pASWD, Nullable<decimal> fONO, string hABILITADO, string rUT_EMPRESA)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var f_NACIMIENTOParameter = f_NACIMIENTO != null ?
                new ObjectParameter("F_NACIMIENTO", f_NACIMIENTO) :
                new ObjectParameter("F_NACIMIENTO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASWDParameter = pASWD != null ?
                new ObjectParameter("PASWD", pASWD) :
                new ObjectParameter("PASWD", typeof(string));
    
            var fONOParameter = fONO.HasValue ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(decimal));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_MEDICO", rUTParameter, nAMEParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, f_NACIMIENTOParameter, eMAILParameter, pASWDParameter, fONOParameter, hABILITADOParameter, rUT_EMPRESAParameter);
        }
    
        public virtual int MODIFICAR_RECOMENDADO(Nullable<decimal> iD_EVAL)
        {
            var iD_EVALParameter = iD_EVAL.HasValue ?
                new ObjectParameter("ID_EVAL", iD_EVAL) :
                new ObjectParameter("ID_EVAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_RECOMENDADO", iD_EVALParameter);
        }
    
        public virtual int MODIFICAR_TIPO_EVALUACION(Nullable<decimal> iDTIPOEV, string nAME, string hABILITADA)
        {
            var iDTIPOEVParameter = iDTIPOEV.HasValue ?
                new ObjectParameter("IDTIPOEV", iDTIPOEV) :
                new ObjectParameter("IDTIPOEV", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var hABILITADAParameter = hABILITADA != null ?
                new ObjectParameter("HABILITADA", hABILITADA) :
                new ObjectParameter("HABILITADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_TIPO_EVALUACION", iDTIPOEVParameter, nAMEParameter, hABILITADAParameter);
        }
    
        public virtual int MODIFICAR_TIPO_USUARIO(Nullable<decimal> iDTIPOUS, string nAME, string hABILITADO)
        {
            var iDTIPOUSParameter = iDTIPOUS.HasValue ?
                new ObjectParameter("IDTIPOUS", iDTIPOUS) :
                new ObjectParameter("IDTIPOUS", typeof(decimal));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var hABILITADOParameter = hABILITADO != null ?
                new ObjectParameter("HABILITADO", hABILITADO) :
                new ObjectParameter("HABILITADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_TIPO_USUARIO", iDTIPOUSParameter, nAMEParameter, hABILITADOParameter);
        }
    
        public virtual int ELIMINAR_DETALLE_EVALUACION(Nullable<decimal> iD_EV)
        {
            var iD_EVParameter = iD_EV.HasValue ?
                new ObjectParameter("ID_EV", iD_EV) :
                new ObjectParameter("ID_EV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_DETALLE_EVALUACION", iD_EVParameter);
        }
    
        public virtual int MODIFICAR_DETALLE_EVALUACION(Nullable<decimal> iD_EVAL, string rECOMND, string aUTORITATION)
        {
            var iD_EVALParameter = iD_EVAL.HasValue ?
                new ObjectParameter("ID_EVAL", iD_EVAL) :
                new ObjectParameter("ID_EVAL", typeof(decimal));
    
            var rECOMNDParameter = rECOMND != null ?
                new ObjectParameter("RECOMND", rECOMND) :
                new ObjectParameter("RECOMND", typeof(string));
    
            var aUTORITATIONParameter = aUTORITATION != null ?
                new ObjectParameter("AUTORITATION", aUTORITATION) :
                new ObjectParameter("AUTORITATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_DETALLE_EVALUACION", iD_EVALParameter, rECOMNDParameter, aUTORITATIONParameter);
        }
    }
}
