//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMENDACIONES_PERSONA_VIEW
    {
        public int CLAVE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OBSERVACION { get; set; }
        public string RECOMENDADA { get; set; }
        public string EMPRESA { get; set; }
        public string CLIENTE { get; set; }
    }
}
