//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOEVALUACION
    {
        public TIPOEVALUACION()
        {
            this.EVALUACION = new HashSet<EVALUACION>();
        }
    
        public int IDTIPO { get; set; }
        public string NOMBRE { get; set; }
        public string HABILITADO { get; set; }
    
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
    }
}
