//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_CITAS_GENERAL
    {
        public int ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public string ASISTENCIA { get; set; }
        public string ACTIVA { get; set; }
        public string EMPRESA { get; set; }
    }
}
